from selenium.webdriver.common.by import By

class PollPageLocators:
    HEADER = (By.CSS_SELECTOR, "h5[data-testid='poll-title']")
    GET_TITLE = (By.CSS_SELECTOR, '[data-testid="poll-title"]')
    POLL_LOCALIZATION = (By.CSS_SELECTOR, "p.text-muted-foregroun.truncate.whitespace-nowrap.text-sm")
    POLL_DESCRIPTION = (By.CSS_SELECTOR, 'p.min-w-0.whitespace-pre-wrap.text-pretty.text-sm.leading-relaxed')
    POLL_DATES_OPTIONS = (By.XPATH, '//div[text()="3 options"]')
    POLL_COMMENTS_MESSAGE = (By.XPATH, "//button[contains(text(), 'Leave a comment on this poll')]")
    POLL_DISABLED_COMMENTS_MESSAGE = (By.XPATH, "//p[contains(text(), 'Comments have been disabled')]")
    ADD_NEW_VOTE_AND_PARTICIPANT = (By.XPATH, '(//svg[contains(@class, "lucide-expand")])[1]')
    ADD_NEW_PARTICIPANT = (By.XPATH, '//button[@data-testid="add-participant-button"]')
    DATE1 = (By.XPATH, "(//button[@data-testid='vote-selector'])[1]")
    DATE2 = (By.XPATH, "(//button[@data-testid='vote-selector'])[2]")
    DATE3 = (By.XPATH, "(//button[@data-testid='vote-selector'])[3]")
    ADD_VOTE_CONTINUE_BUTTON = (By.XPATH, "//button[text()='Continue']")
    NEW_PARTICIPANT_NAME = (By.NAME, "name")
    NEW_PARTICIPANT_EMAIL = (By.NAME, "email")
    NEW_PARTICIPANT_SUBMIT = (By.XPATH, "//button[text()='Submit']")
    MODAL_ROOT = (By.CSS_SELECTOR, "div[role='dialog'][data-state='open']")
    ICONS_NUMBER_OF_MEMBERS = (By.CSS_SELECTOR, "span.inline-flex.items-center.text-xs")
    EDIT_VOTES_BUTTON = (By.XPATH, "//span[normalize-space()='Edit votes']")
    CHOOSE_VOTE_EDIT_VOTE_BUTTON = (By.XPATH, "(//button[@data-testid='vote-selector'])[1]")
    SAVE_EDIT_VOTES_BUTTON = (By.XPATH, "//button[@type='submit' and @form='voting-form' and normalize-space()='Save']")
    NUMBER_OF_VOTES_INITIAL = (By.XPATH, "(//span[contains(@class, 'inline-flex')])[1]/span")  # nie działa poki co mi
    MEMBERS_ICON_SPAN = (By.TAG_NAME, "span")
    COLOR_OF_VOTED_ICON = (By.CSS_SELECTOR, "td.h-12 div.inline-flex svg path")
    COLOR_OF_NO_VOTE_ICON_LEGEND = (By.CSS_SELECTOR, "ul.flex.items-center li:nth-child(3) svg path")
    COLOR_OF_YES_VOTE_ICON_LEGEND = (By.CSS_SELECTOR, "ul.flex.items-center li:nth-child(1) svg path")
    COLOR_OF_IFNEEDBE_VOTE_ICON_LEGEND = (By.CSS_SELECTOR, "ul.flex.items-center li:nth-child(2) svg path")
    DELETE_PARTICIPANT = (By.XPATH, "//div[@role='menuitem' and contains(., 'Delete')]")
    MODAL_TO_DELETE_PARTICIPANT = (By.CSS_SELECTOR, "div[role='dialog'][data-state='open']")
    DELETE_PARTICIPANT_MODAL = (By.XPATH, ".//button[normalize-space()='Delete']")
    NO_PARTICIPANT_LABEL = (By.XPATH, '//p[normalize-space()="No participants"]')
    COMMENT_BUTTON = (By.XPATH, "//button[text()='Leave a comment on this poll (visible to everyone)']")
    COMMENT_AUTHOR_NAME = (By.NAME, "authorName")
    ADD_COMMENT_BUTTON = (By.XPATH, "//button[text()='Add Comment']")
    COMMENT_TEXT_ADDED = (By.CSS_SELECTOR, "div.w-fit.whitespace-pre-wrap.pl-7.text-sm.leading-relaxed")
    COMMENTS = (By.CSS_SELECTOR, "div[data-testid='comment']")  # kontener pojedynczego komentarza
    DOTS_BUTTON = (By.CSS_SELECTOR, "button > svg.lucide-ellipsis")
    GO_UP_ONE_LEVEL = (By.XPATH, "..")
    COMMENT_TEXT_INPUT = (By.NAME, "content")
    COMMENT_ELEMENTS = (By.CSS_SELECTOR, '[data-testid="comment"]')
    COMMENT_AUTHOR = (By.CSS_SELECTOR, "div.truncate.text-sm.font-medium")
    DELETE_COMMENT_BUTTON = (By.XPATH, "//div[@role='menuitem' and contains(text(),'Delete')]")
    MANAGE_BUTTON = (By.XPATH, "//span[contains(text(), 'Manage')]/parent::button")
    PAUSE_BUTTON = (By.XPATH, "//div[@role='menuitem' and contains(text(), 'Pause')]")
    RESUME_LABEL = (By.XPATH, "//span[contains(text(), 'Paused')]")
    ACTIVE_LABEL = (By.XPATH, '//span[contains(text(), "Live")]')
    RESUME_BUTTON = (By.XPATH, "//div[@role='menuitem' and normalize-space()='Resume']")
    DELETE_BUTTON = (By.XPATH, "//div[@role='menuitem' and text()='Delete']")
    CONFIRM_DELETE_BUTTON = (By.XPATH, "//button[text()='Delete']")